### ISSUE TITLE
nsqio move

### ISSUE THREAD

**Issue by mreiferson** [nsqio/nsqio.github.io#1]
- [x] move `nsq-java`
- [x] move `pynsq`
  - [x] merge [https://github.com/bitly/pynsq/compare/bitly:master...mreiferson:nsqio](https://github.com/bitly/pynsq/compare/bitly:master...mreiferson:nsqio) updating metadata/docs
  - [x] `python setup.py register`
- [x] move `go-nsq`
  - [x] merge [https://github.com/bitly/go-nsq/compare/bitly:master...mreiferson:nsqio](https://github.com/bitly/go-nsq/compare/bitly:master...mreiferson:nsqio) updating docs
- [x] move `nsq`
  - [x] merge [https://github.com/bitly/nsq/compare/bitly:master...mreiferson:nsqio](https://github.com/bitly/nsq/compare/bitly:master...mreiferson:nsqio) updating import paths/docs
- [x] merge `nsqio.github.io` [https://github.com/nsqio/nsqio.github.io/pull/2](https://github.com/nsqio/nsqio.github.io/pull/2) updating links to repos
- [x] publish announcement post
- [x] update twitter avatar
- [x] update github avatar
- [x] update docker registry avatar
- [ ] send announcement tweet (link to post http://nsq.io/blog/were_moving.html)
- [x] send announcement to mailing list (link to post http://nsq.io/blog/were_moving.html)

/cc @jehiah

**Comment by mreiferson** [comment]
## We're Moving

The official NSQ repositories are now under the [`nsqio`](https://github.com/nsqio) GitHub organization!

NSQ has grown from its humble beginnings and is now powering the infrastructure of many companies, such as [Hailo](https://hailo.com), [Segment](https://segment.com), [Docker](https://docker.com), and of course [Bitly](https://bitly.com). Having its own independent organization ensures that it will continue to grow and meet future needs as a community-run project.

### Logistics

For most users, the move should have no material impact beyond updating `git` remotes.

For users of `go-nsq` this unfortunately means that `import` paths will need to be updated (sorry!).

### Looking Ahead

This also marks the beginning of a refocussed effort to reach `v1.0` stability. _We want to hear from you!_ We've got a pretty good idea of what `v1.0` means to us but this is your chance to let us know what features you think should be prioritized.  Start a discussion on the [mailing list](https://groups.google.com/forum/#!forum/nsq-users) or the [issue tracker](https://github.com/nsqio/nsq/issues).

In the coming weeks we'll publish our anticipated roadmap and outline some key features (and deprecations) we hope to include in that eventual release.

Finally, we'd like to thank the NSQ community for all your support! Without you this wouldn't be possible.

Here's to a bright future.

-- [@nsqio](https://twitter.com/nsqio)

**Comment by jehiah** [comment]
:coffee: :boom:

**Comment by mreiferson** [comment]
added post to #2
