### ISSUE TITLE
nsqlookupd is missing a bunch of http api documentation

### ISSUE THREAD

**Issue by stephensearles** [nsqio/nsqio.github.io#13]
Unless I'm missing something, I think there's a bunch of extremely handy functionality that's not called out on the website. Specifically, nsqlookupd seems to support a handful of the same HTTP API that nsqd does, though with a couple minor differences. (e.g. /channel/create on nsqlookupd will implicitly create a nonexistent topic, but nsqd will not)

**Comment by mreiferson** [comment]
In my mind this is intentional as we didn't really want to encourage use or dependency on this API.

**Comment by stephensearles** [comment]
The use case is that with producing nodes coming online, I don't know which topics and channels I should create there, but I do know things like: "topic X will always need to go to channels Y and Z". In an ongoing cluster, a new `nsqd` will learn about this association from `lookupd`, which itself learns the associations by eventually hearing about all the subscribers. In a fresh cluster, though, if I'm not sure ahead of time which topics will be produced on a given node, I don't know which topics I should inform `nsqd` about, but I do have to tell it about topics to make channel associations. If I tell `lookupd` directly instead of going through `nsqd`, I just create the associations that will inform `nsqd` and I avoid some extra setup work and potential risks like idle TCP connections.

I suppose an alternative would be to allow creating channels in nsqd without requiring a topic. Thoughts?

**Comment by mreiferson** [comment]
I suppose there isn't harm in documenting these given we're planning on providing a compatibility promise through `1.0`.

@stephensearles are you interested in taking a pass?

**Comment by ploxiln** [comment]
looks like I added the nsqlookupd create endpoints in #29 and updated them in #35
