### ISSUE TITLE
docs: /put should now /pub in quick start

### ISSUE THREAD

**Issue by gr4finger** [nsqio/nsqio.github.io#14]
Just wanted to inform you about an error in NSQ QUICK START guide
The example for publishing a message using curl says:
$ curl -d 'hello world 1' 'http://127.0.0.1:4151/put?topic=test'.

This results into an error. The right URL should be "pub" (not "put")
$ curl -d 'hello world 1' 'http://127.0.0.1:4151/pub?topic=test'.

Same error (copy&paste) also in "hello world 2" and "hello world 3".
cheers,
Andreas

**Comment by mreiferson** [comment]
@gr4finger would you like to just go ahead and make the change in a PR?

**Comment by andyxning** [comment]
@mreiferson @gr4finger 

Find this issue later. I have make an PR to update `put` to `pub` in #15 . :)
