### ISSUE TITLE
docs: add /ping endpoint

### ISSUE THREAD

**Issue by mreiferson** [nsqio/nsqio.github.io#36]
see https://github.com/nsqio/nsq/issues/995

**Comment by ploxiln** [comment]
These have been documented for nsqd and nsqlookupd for a while:

https://nsq.io/components/nsqd.html#get-ping
https://nsq.io/components/nsqlookupd.html#get-ping

We don't explicitly document any http endpoints for nsqadmin because it's only intended as a UI, not an API, I think.
