### ISSUE TITLE
Documentation: Quickstart opens nsqadmin at a different port and instructs to open at a different one.

### ISSUE THREAD

**Issue by abhsag24** [nsqio/nsqio.github.io#52]
Hey, 

I was just starting out and I noticed that the quick start guide instructs you to open nsqadmin at port 4161 but expects you to connect at 4171 to view the UI. Am I missing something here? apologies in advance if i've got it wrong.

**Comment by ploxiln** [comment]
This command-line option flag:

```
nsqadmin --lookupd-http-address=127.0.0.1:4161
```

tells nsqadmin to connect to nsqlookupd on its default port, 4161. nsqadmin still listens on its default port of 4171.

(To change the port that nsqdmin listens on, you would  use the option flag `--http-address=<desired-ip:port-here>`)

**Comment by abhsag24** [comment]
thank you clears up things :D
