### ISSUE TITLE
doc: the default value of heartbeat_interval wrong

### ISSUE THREAD

**Issue by ctlove0523** [nsqio/nsqio.github.io#82]
current:
~~~
Defaults to --client-timeout / 2
~~~
actually value is 60s

**Comment by mreiferson** [comment]
You're right that the default _max_ heartbeat interval for `nsqd` is `60s`, however `heartbeat_interval` is a per-client setting that is based on `--client-timeout`.

See: https://github.com/nsqio/nsq/blob/master/nsqd/client_v2.go#L218
